// Generated by CoffeeScript 2.7.0
(function() {
  window.requestAnimFrame = (function() {
    // probably overkill
    return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(cb) {
      return window.setTimeout(cb, 1000 / 60);
    };
  })();

  $(function() {
    var getWebcam;
    getWebcam = function() {
      var deferred;
      deferred = $.Deferred();
      navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia;
      if (navigator.getUserMedia) {
        navigator.getUserMedia('video', deferred.resolve, deferred.reject);
      } else {
        deferred.reject();
      }
      return deferred.promise();
    };
    return getWebcam().pipe(function(stream) {
      var ctx, deferred, source, vid, windowurl;
      source = $("canvas").get(0);
      ctx = source.getContext("2d");
      deferred = $.Deferred();
      vid = document.createElement("video");
      windowurl = window.URL || window.webkitURL;
      vid.src = windowurl ? windowurl.createObjectURL(stream) : stream;
      $(vid).on("loadedmetadata", function() {
        var div;
        div = 1;
        ctx.canvas.width = vid.videoWidth / div;
        return ctx.canvas.height = vid.videoHeight / div;
      });
      $(vid).on("canplay", function() {
        return deferred.resolve(ctx, vid);
      });
      $(vid).on("error", function() {
        return deferred.reject();
      });
      vid.loop = vid.muted = true;
      vid.load();
      vid.play();
      return deferred.promise();
    }).then(function(ctx, vid) {
      var draw;
      draw = function() {
        var pixels;
        requestAnimFrame(draw);
        ctx.drawImage(vid, 0, 0, ctx.canvas.width, ctx.canvas.height);
        pixels = ctx.getImageData(0, 0, ctx.canvas.width, ctx.canvas.height);
        return ctx.putImageData(process(pixels), 0, 0);
      };
      return draw();
    }).fail(function(err) {
      return alert("could not get webcam");
    });
  });

}).call(this);
